Print 64-bit counters using PRIu64 from inttypes.h
Printing uint64_t (long long unsigned int on 32-bit architectures)
cannot be done using the %lu specifier. It causes build errors like
below:

dpmac_commands.c: In function ‘print_dpmac_counters’:
dpmac_commands.c:330:17: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]
  330 |   printf("%s: %lu\n", dpaa2_mac_counters[i].name, counter_value);
      |               ~~^                                 ~~~~~~~~~~~~~
      |                 |                                 |
      |                 long unsigned int                 uint64_t {aka long long unsigned int}
      |               %llu

Note that in print_dpsw_endpoint() from dpsw_commands.c, we were
printing the DPSW counters as signed (%ld), although their data type was
also uint64_t. Fix that in the same process of converting to PRIu64.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>