Avoid use of non-portable __WORDSIZE when defining BITS_PER_LONG
Here is the location of __WORDSIZE in various buildroot toolchains:
- glibc, uclibc: /usr/include/bits/wordsize.h
- musl: /usr/include/bits/reg.h

Actually musl defines no <bits/wordsize.h> and I don't see any way in
which we could easily support all toolchain locations of this definition.

Furthermore, <bits/reg.h> is not transitively included by musl, so
compilation currently fails as can be seen below:

In file included from mc_v10/dpdbg.c:35:
mc_v10/dpdbg.c: In function ‘dpdbg_set_ctlu_profiling_counters’:
mc_v10/fsl_mc_cmd.h:55:23: error: ‘__WORDSIZE’ undeclared (first use in this function)
   55 | #define BITS_PER_LONG __WORDSIZE
      |                       ^~~~~~~~~~
mc_v10/fsl_mc_cmd.h:60:33: note: in expansion of macro ‘BITS_PER_LONG’
   60 |          (~(unsigned long)0 >> (BITS_PER_LONG - 1 - (h))))
      |                                 ^~~~~~~~~~~~~
mc_v10/fsl_dpdbg_cmd.h:63:9: note: in expansion of macro ‘GENMASK’
   63 |         GENMASK(DPDBG_##field##_SHIFT + DPDBG_##field##_SIZE - 1, \
      |         ^~~~~~~
mc_v10/fsl_dpdbg_cmd.h:67:55: note: in expansion of macro ‘DPDBG_MASK’
   67 |         ((var) |= (((val) << DPDBG_##field##_SHIFT) & DPDBG_MASK(field)))
      |                                                       ^~~~~~~~~~

and many others.

For the architectures we care about, the __WORDSIZE (32 or 64) can
simply and portably be derived from the size in bytes of a pointer,
multiplied by the size in bits of a byte.

Fixes: 66d941a0160d ("Adapt BITS_PER_LONG and GENMASK() definitions for 32-bit compatibility")
Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>